#!/bin/bash
gcc-S-masm=intel$CFILE
root@b974b8789248:/alx-low_level_programming/0x00-hello_world#cat101-quote.c
#include<unistd.h>
/**
*main-GuessWhat!!??ThisisaDescription
*Return:0(Success)
*/
intmain(void)
{
write(2,"andthatpieceofartisuseful\"-DoraKorpar,2015-10-19\n",59);
return(1);
}
