#include<stdio.h>
/**
*main-GuessWhat!!??ThisisaDescription
*Return:0(Success)
*/
intmain(void)
{
chara;
intb;
longintc;
longlongintd;
floatf;
printf("Sizeofachar:%lubyte(s)\n",(unsignedlong)sizeof(a));
printf("Sizeofanint:%lubyte(s)\n",(unsignedlong)sizeof(b));
printf("Sizeofalongint:%lubyte(s)\n",(unsignedlong)sizeof(c));
printf("Sizeofalonglongint:%lubyte(s)\n",(unsignedlong)sizeof(d));
printf("Sizeofafloat:%lubyte(s)\n",(unsignedlong)sizeof(f));
return(0);
}
